# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D877-LzBjB7ZH95tJgvMt1vRR49ReS5_
"""

def process_command(command):
    if "lights" in command:
        if "turn on" in command:
            print("Turning on lights...")
            # Code to turn on lights
        elif "turn off" in command:
            print("Turning off lights...")
            # Code to turn off lights
        else:
            print("Sorry, I didn't understand that light command.")
    elif "temperature" in command:
        if "increase" in command:
            print("Increasing temperature...")
            # Code to increase temperature
        elif "decrease" in command:
            print("Decreasing temperature...")
            # Code to decrease temperature
        else:
            print("Sorry, I didn't understand that temperature command.")
    elif "fan" in command:
        if "turn on" in command:
            print("turning on fan...")
            # Code to increase temperature
        elif "turn off" in command:
            print("turning off fan...")
            # Code to decrease temperature
        else:
            print("Sorry, I didn't understand that temperature command.")
    else:
        print("Sorry, I didn't understand that command.")
x=input("enter your name\n")
while True:
    user_input = input("Please give a command: ").lower()
    if user_input == "exit":
        print("Exiting program...")
        break
    else:
        process_command(user_input)